### ISSUE TITLE
BAD_DATA in eth_getTransactionReceipt

### ISSUE THREAD

**Issue by zer0-deaths** [hypersound-money/miner#3]
I keep getting this error when running the miner. It was fine the first few days and now I keep getting every time I sent a few transactions. I tried to remove and rebuilt it but didnt help. Any suggestions?

/home/user/miner/node_modules/ethers/lib.commonjs/utils/errors.js:129
            error = new Error(message);
                    ^

Error: missing response for request (value=[ { "error": { "code": 0, "message": "we can't execute this request" }, "id": null, "jsonrpc": "2.0" } ], info={ "payload": { "id": 39, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "#`$$$TXN$$$`" ] } }, code=BAD_DATA, version=6.13.2)
    at makeError (/home/user/miner/node_modules/ethers/lib.commonjs/utils/errors.js:129:21)
    at /home/user/miner/node_modules/ethers/lib.commonjs/providers/provider-jsonrpc.js:293:72
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'BAD_DATA',
  value: [
    {
      jsonrpc: '2.0',
      error: { code: 0, message: "we can't execute this request" },
      id: null
    }
  ],
  info: {
    payload: {
      method: 'eth_getTransactionReceipt',
      params: [
        '#`$$$TXN$$$`'
      ],
      id: 39,
      jsonrpc: '2.0'
    }
  },
  shortMessage: 'missing response for request'
}

**Comment by hypersound-money** [comment]
This is most likely an RPC issue, try another RPC provider

**Comment by zer0-deaths** [comment]
That worked, thank you very much for the quick response.
